const SIGNAL_LABELS: Readonly<Record<string, string>> = {
  'taiwan-mnd': 'Taiwan Ministry of National Defense',
  'japan-mod': 'Japan Ministry of Defense',
  plaAircraftSorties: 'Chinese military aircraft flights',
  plaAircraft: 'Chinese military aircraft',
  planShips: 'Chinese navy ships',
  officialShips: 'Other official vessels',
  russianNavyShips: 'Russian navy ships',
  medianLineCrossings: 'Taiwan Strait median-line crossings',
  adizEntries: 'Air defense identification zone entries',
  PLA: "China's armed forces",
  PLAN: 'Chinese navy',
  ADIZ: 'Air defense identification zone',
  MND: 'Ministry of National Defense',
  CAC: 'Cyberspace Administration of China',
  SAMR: 'State Administration for Market Regulation',
  MOFCOM: 'Ministry of Commerce',
  MIIT: 'Ministry of Industry and Information Technology',
  NDRC: 'National Development and Reform Commission',
  PBOC: "People's Bank of China",
  NBS: 'National Bureau of Statistics',
  SAFE: 'State Administration of Foreign Exchange',
  CSRC: 'China Securities Regulatory Commission',
  SSE: 'Shanghai Stock Exchange',
  SZSE: 'Shenzhen Stock Exchange',
  BSE: 'Beijing Stock Exchange',
  HKEX: 'Hong Kong Exchanges and Clearing',
  YoY: 'year over year',
  MoM: 'month over month',
  QoQ: 'quarter over quarter',
  GDP: 'gross domestic product',
  PMI: 'purchasing managers index',
  CPI: 'consumer price index',
  PPI: 'producer price index',
  USD: 'US dollars',
  announcement_guidance: 'Announcement or guidance',
  final_rule: 'Final rule',
  draft_rule: 'Draft rule',
  consultation_draft: 'Draft for consultation',
  administrative_approval_restriction: 'Administrative approval or restriction',
  enforcement_action: 'Enforcement action',
  enforcement_penalty: 'Enforcement penalty',
  effective_date_change: 'Effective date changed',
  amendment_correction_repeal_supersession: 'Amendment, correction, repeal or replacement',
  in_force: 'In force',
  under_investigation: 'Under investigation',
  mixed_signals: 'Mixed signals',
  power_energy: 'Power and energy',
  healthy_quiet_window: 'No qualifying events in this reporting period',
  insufficient_data: 'Not enough data',
  upstream_unavailable: 'Source unavailable',
};

const SIGNAL_TOKENS = new RegExp(`\\b(${Object.keys(SIGNAL_LABELS).join('|')})\\b`, 'g');

export function formatChinaSignalText(value: string): string {
  return value.replace(SIGNAL_TOKENS, token => SIGNAL_LABELS[token]!);
}
